name: flutter_shader
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  shaders:
    - shaders/show_image.frag
    - shaders/nega_posi_reverse.frag
    - shaders/cross_fading.frag
    - shaders/uv.frag
  # SHADER

    - shaders/over_the_moon/vector_line.frag
    - shaders/over_the_moon/cross_line.frag
    - shaders/over_the_moon/top_white.frag
    - shaders/over_the_moon/white_line.frag
    - shaders/over_the_moon/white_box.frag
    - shaders/over_the_moon/trapezium.frag
    - shaders/over_the_moon/trunk.frag
    - shaders/over_the_moon/tree.frag
    - shaders/over_the_moon/tree_function.frag
    - shaders/over_the_moon/shadow.frag
    - shaders/over_the_moon/uv_fix.frag
    - shaders/over_the_moon/shadow_fix.frag
    - shaders/over_the_moon/repeat_tree.frag
    - shaders/over_the_moon/random_place.frag
    - shaders/over_the_moon/move_in_time.frag
    - shaders/over_the_moon/random_size.frag
    - shaders/over_the_moon/flat_ground.frag
    - shaders/over_the_moon/gentle_ground.frag
    - shaders/over_the_moon/stragiht_tree.frag
    - shaders/over_the_moon/multiple_layer.frag
    - shaders/over_the_moon/motion_parallax.frag
    - shaders/over_the_moon/follow_drag.frag
    - shaders/over_the_moon/atmospheric_perspective.frag
    - shaders/over_the_moon/fix_edge.frag
  # MOON

    - shaders/pixel_spirit_deck/justice.frag
    - shaders/pixel_spirit_deck/strength.frag
    - shaders/pixel_spirit_deck/death.frag
  # SPIRIT
